### ISSUE TITLE
Is this repo applicable now?

### ISSUE THREAD

**Issue by rubujubi** [as5845131421/NMlab_final-Anti-Money-Laundering-in-Bitcoin#1]
Hi, 
As I didn't find your e-mail address, I created an issue. I was reading _Anti-Money Laundering in Bitcoin: Experimenting with Graph Convolutional Networks for Financial Forensics_ and found your repo. I want to ask is this the implementation for this paper? Is it applicable now?
Thanks in advance!

**Comment by as5845131421** [comment]
Hi,
This is not the implementation of the paper. This repo is just a small project for my school course.

**Comment by YC-Hsiung** [comment]
Hi, Kindhearted57
Yes, this repo is working on elliptic dataset. GAT.py can get not bad performance, but I don't think it is good enough. This is just a small project for my school course this semester, so I think I won't update this repo after this month. However, I'm still trying different methods.

**Comment by rubujubi** [comment]
Thanks for your effort!! 😆 Helps a lot.
